export const BUY_NOW = 'BUY_NOW';
export const MODIFY_PRODUCT = 'MODIFY_PRODUCT'
export const MODIFY_CART_COUNT = 'MODIFY_CART_COUNT' 
export const MODIFY_CART_TOTAL_PRICE = 'MODIFY_CART_TOTAL_PRICE' 



